#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render the profile header and ecosystem map SVGs from ``profile-data.json``.

Every count, name and tagline in the two images comes from the manifest, so the
pictures cannot drift from the README tables that the validator already gates.
Text is emitted as glyph outlines of Space Grotesk (``assets/fonts``), because
GitHub's image proxy loads no external fonts and system fallbacks differ per
platform. Each SVG carries a machine-readable ``<desc>`` line with the counts it
was rendered from; ``validate_profile.py`` compares that line with the manifest.

Usage: ``python3 tools/render_profile_assets.py [--check]``

``--check`` renders in memory and exits 1 when any file on disk differs from a
fresh render (the CI drift gate). Requires ``fonttools`` and ``brotli``
(``tools/requirements-render.txt``).
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "profile-data.json"
FONT_FILES = (
    ROOT / "assets" / "fonts" / "space-grotesk-latin.woff2",
    ROOT / "assets" / "fonts" / "space-grotesk-latin-ext.woff2",
)
OUTPUTS = {
    ("header", "dark"): ROOT / "assets" / "profile-header-dark.svg",
    ("header", "light"): ROOT / "assets" / "profile-header-light.svg",
    ("map", "dark"): ROOT / "assets" / "ecosystem-map-dark.svg",
    ("map", "light"): ROOT / "assets" / "ecosystem-map-light.svg",
}
SVG_NAMESPACES = 'xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"'
LICENCE_HEADER = """<!--
SPDX-License-Identifier: AGPL-3.0-or-later
Commercial licence available
© Concepts 1996–2026 Miroslav Šotek. All rights reserved.
© Code 2020–2026 Miroslav Šotek. All rights reserved.
ORCID: 0009-0009-3560-0851
Contact: www.anulum.li | protoscience@anulum.li
{purpose} (generated by tools/render_profile_assets.py; do not edit by hand)
-->
"""


@dataclass(frozen=True)
class Slot:
    """Card position on the 1200x700 map and which count the card shows."""

    x: int
    y: int
    w: int
    h: int
    accent: str
    count: str


# Portfolio id -> card slot. The layout is fixed; the numbers and words inside
# each slot come from the manifest.
MAP_SLOTS = {
    "reactor": Slot(60, 105, 340, 150, "gold", "public"),
    "neuromorphic": Slot(430, 105, 340, 150, "slate", "public"),
    "quantum": Slot(800, 105, 340, 150, "slate", "public"),
    "integration-control": Slot(315, 330, 570, 116, "gold", "total"),
    "agentic": Slot(240, 514, 720, 120, "teal", "total"),
}

THEMES: dict[str, dict[str, str]] = {
    "dark": {
        "bg0": "#09111f",
        "bg1": "#111d32",
        "bg2": "#071821",
        "grid": "#62748f",
        "text": "#f4f7fb",
        "muted": "#b8c5d8",
        "faint": "#7f92ad",
        "label": "#9fb0c7",
        "gold": "#d9a441",
        "gold2": "#f1d28a",
        "teal": "#4dd6c8",
        "teal2": "#279d98",
        "tealtext": "#70e0d5",
        "slate": "#7992b5",
        "card": "#111f34",
        "card_gold": "#102735",
        "card_teal": "#0d2930",
        "node": "#0d1727",
        "halo_opacity": "0.19",
        "grid_opacity": "0.24",
    },
    "light": {
        "bg0": "#f7f9fc",
        "bg1": "#ffffff",
        "bg2": "#eef3f7",
        "grid": "#62748f",
        "text": "#0b1220",
        "muted": "#3e4d63",
        "faint": "#5b6b84",
        "label": "#4a5a72",
        "gold": "#b07d1e",
        "gold2": "#d9a441",
        "teal": "#1f9a91",
        "teal2": "#167a73",
        "tealtext": "#167a73",
        "slate": "#6b84a8",
        "card": "#ffffff",
        "card_gold": "#fffaf0",
        "card_teal": "#f0fbfa",
        "node": "#ffffff",
        "halo_opacity": "0.14",
        "grid_opacity": "0.18",
    },
}


@dataclass(frozen=True)
class Counts:
    """Repository counts derived from the manifest."""

    portfolios: int
    repositories: int
    public: int
    private: int
    standalone: int
    verified_at: str
    per_portfolio: dict[str, tuple[int, int]]

    def desc(self) -> str:
        """Return the machine-readable count line embedded in every SVG."""
        groups = " ".join(f"{key}={public}/{private}" for key, (public, private) in self.per_portfolio.items())
        return (
            f"counts: portfolios={self.portfolios} repositories={self.repositories} "
            f"public={self.public} private={self.private} standalone={self.standalone} "
            f"verified={self.verified_at}; {groups}"
        )


def load_counts(data: dict[str, Any]) -> Counts:
    """Derive every rendered number from the manifest."""
    per: dict[str, tuple[int, int]] = {}
    for portfolio in data["portfolios"]:
        repos = portfolio["repositories"]
        public = sum(1 for repo in repos if repo["access"] == "public")
        private = sum(1 for repo in repos if repo["access"] == "private")
        per[portfolio["id"]] = (public, private)
    return Counts(
        portfolios=len(data["portfolios"]),
        repositories=sum(p + q for p, q in per.values()),
        public=sum(p for p, _ in per.values()),
        private=sum(q for _, q in per.values()),
        standalone=len(data["standalone_repositories"]),
        verified_at=data["verified_at"],
        per_portfolio=per,
    )


class Typesetter:
    """Convert text runs into SVG path groups using the bundled variable font."""

    def __init__(self, font_files: tuple[Path, ...]) -> None:
        self._files = font_files
        self._instances: dict[tuple[Path, int], tuple[Any, dict[int, str], int]] = {}
        self._defs: dict[str, str] = {}

    def reset(self) -> None:
        """Forget the glyph definitions collected for the previous document."""
        self._defs = {}

    def defs(self) -> str:
        """Return one ``<path>`` definition per glyph used since :meth:`reset`."""
        return "".join(f'<path id="{key}" d="{d}"/>' for key, d in sorted(self._defs.items()))

    def _instance(self, path: Path, weight: int) -> tuple[Any, dict[int, str], int]:
        key = (path, weight)
        if key not in self._instances:
            font = TTFont(str(path))
            static = instancer.instantiateVariableFont(font, {"wght": weight})
            self._instances[key] = (static.getGlyphSet(), static.getBestCmap(), static["head"].unitsPerEm)
        return self._instances[key]

    def _glyph(self, char: str, weight: int) -> tuple[Any, str, int] | None:
        for path in self._files:
            glyph_set, cmap, upm = self._instance(path, weight)
            name = cmap.get(ord(char))
            if name is not None:
                return glyph_set, name, upm
        return None

    def measure(self, text: str, size: float, weight: int, letter_spacing: float = 0.0) -> float:
        """Return the advance width of ``text`` in user units."""
        width = 0.0
        for char in text:
            found = self._glyph(char, weight)
            if found is None:
                raise ValueError(f"glyph missing in bundled fonts: {char!r}")
            glyph_set, name, upm = found
            width += glyph_set[name].width * size / upm + letter_spacing
        return width - letter_spacing if text else 0.0

    def run(
        self,
        text: str,
        x: float,
        y: float,
        *,
        size: float,
        weight: int,
        fill: str,
        letter_spacing: float = 0.0,
        anchor: str = "start",
    ) -> str:
        """Return a ``<g>`` of glyph outlines for ``text`` with its baseline at ``y``."""
        width = self.measure(text, size, weight, letter_spacing)
        if anchor == "middle":
            x -= width / 2
        elif anchor == "end":
            x -= width
        parts: list[str] = []
        advance = 0.0
        for char in text:
            found = self._glyph(char, weight)
            assert found is not None
            glyph_set, name, upm = found
            glyph = glyph_set[name]
            scale = size / upm
            key = f"g{weight}-{name}"
            if key not in self._defs:
                pen = SVGPathPen(glyph_set, ntos=lambda value: f"{value:.0f}")
                glyph.draw(pen)
                self._defs[key] = pen.getCommands()
            if self._defs[key]:
                parts.append(
                    f'<use xlink:href="#{key}" '
                    f'transform="translate({x + advance:.1f} {y:.1f}) scale({scale:.5f} {-scale:.5f})"/>'
                )
            advance += glyph.width * scale + letter_spacing
        label = text.replace("&", "&amp;").replace("<", "&lt;")
        return f'<g fill="{fill}" aria-label="{label}">{"".join(parts)}</g>'


def render_header(data: dict[str, Any], theme: str, typeset: Typesetter, counts: Counts) -> str:
    """Render the 1200x320 profile header."""
    palette = THEMES[theme]
    profile = data["profile"]
    name = profile["name"].upper()
    tagline = profile["tagline"]
    subtitle = profile["subtitle"]
    typeset.reset()
    text_runs = "\n".join(
        [
            typeset.run(name, 72, 139, size=54, weight=650, fill=palette["text"], letter_spacing=2),
            typeset.run(tagline, 75, 189, size=22, weight=450, fill=palette["muted"], letter_spacing=5),
            typeset.run(subtitle, 75, 236, size=17, weight=400, fill=palette["faint"], letter_spacing=1.2),
        ]
    )
    licence = LICENCE_HEADER.format(purpose=f"Personal GitHub profile header, {theme} theme")
    return f"""{licence}<svg {SVG_NAMESPACES} width="1200" height="320" viewBox="0 0 1200 320"
     role="img" aria-labelledby="title description">
  <title id="title">{profile["name"]}</title>
  <desc id="description">{tagline.title()}. {counts.desc()}</desc>
  <defs>
    {typeset.defs()}
    <linearGradient id="background" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{palette["bg0"]}"/>
      <stop offset="0.52" stop-color="{palette["bg1"]}"/>
      <stop offset="1" stop-color="{palette["bg2"]}"/>
    </linearGradient>
    <linearGradient id="signal" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="{palette["gold"]}"/>
      <stop offset="0.48" stop-color="{palette["gold2"]}"/>
      <stop offset="1" stop-color="{palette["teal"]}"/>
    </linearGradient>
    <radialGradient id="halo">
      <stop offset="0" stop-color="{palette["teal"]}" stop-opacity="{palette["halo_opacity"]}"/>
      <stop offset="1" stop-color="{palette["teal"]}" stop-opacity="0"/>
    </radialGradient>
    <filter id="softGlow" x="-80%" y="-80%" width="260%" height="260%">
      <feGaussianBlur stdDeviation="5" result="blur"/>
      <feMerge>
        <feMergeNode in="blur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>

  <rect width="1200" height="320" rx="24" fill="url(#background)" stroke="{palette["grid"]}" stroke-opacity="0.3"/>
  <circle cx="1040" cy="150" r="230" fill="url(#halo)"/>

  <g fill="none" stroke="{palette["grid"]}" stroke-opacity="{palette["grid_opacity"]}" stroke-width="1">
    <path d="M0 72H1200M0 160H1200M0 248H1200"/>
    <path d="M120 0V320M360 0V320M600 0V320M840 0V320M1080 0V320"/>
  </g>

  <g transform="translate(920 55)" fill="none" stroke-linecap="round">
    <circle cx="120" cy="105" r="82" stroke="{palette["teal"]}" stroke-opacity="0.3" stroke-width="1.5"/>
    <circle cx="120" cy="105" r="51" stroke="{palette["gold"]}" stroke-opacity="0.36" stroke-width="1.5"/>
    <path d="M38 105H202M120 23V187M62 47L178 163M178 47L62 163" stroke="{palette["slate"]}" stroke-opacity="0.27"/>
    <path d="M64 139C86 72 129 57 181 85C148 95 130 127 119 164C101 143 83 135 64 139Z"
          stroke="url(#signal)" stroke-width="3"/>
    <g fill="{palette["node"]}" stroke-width="3" filter="url(#softGlow)">
      <circle cx="64" cy="139" r="7" stroke="{palette["gold"]}"/>
      <circle cx="181" cy="85" r="7" stroke="{palette["teal"]}"/>
      <circle cx="119" cy="164" r="7" stroke="{palette["gold2"]}"/>
      <circle cx="120" cy="56" r="5" stroke="{palette["slate"]}"/>
    </g>
  </g>

  <rect x="72" y="66" width="84" height="4" rx="2" fill="url(#signal)"/>
{text_runs}
</svg>
"""


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun[:-1]}ies" if noun.endswith("ry") else f"{count} {noun}s"


def render_map(data: dict[str, Any], theme: str, typeset: Typesetter, counts: Counts) -> str:
    """Render the 1200x700 portfolio ecosystem map."""
    palette = THEMES[theme]
    by_id = {portfolio["id"]: portfolio for portfolio in data["portfolios"]}
    missing = set(MAP_SLOTS) ^ set(by_id)
    if missing:
        raise ValueError(f"map slots and manifest portfolios differ: {sorted(missing)}")

    typeset.reset()
    cards: list[str] = []
    for key, slot in MAP_SLOTS.items():
        portfolio = by_id[key]
        public, private = counts.per_portfolio[key]
        accent = slot.accent
        stroke = palette[accent]
        bar = "url(#gold)" if accent == "gold" else "url(#teal)" if accent == "teal" else palette["slate"]
        fills = {
            "gold": palette["card_gold"] if slot.count == "total" else palette["card"],
            "teal": palette["card_teal"],
            "slate": palette["card"],
        }
        fill = fills[accent]
        x, y, w, h = slot.x, slot.y, slot.w, slot.h
        parts = [
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="18" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="2"/>',
            f'<rect x="{x}" y="{y}" width="8" height="{h}" rx="4" fill="{bar}"/>',
        ]
        title = portfolio["short_name"]
        if slot.count == "public":
            number_fill = palette["gold2"] if accent == "gold" else palette["muted"]
            title_size = 21 if accent == "gold" else 19
            parts.append(typeset.run(title, x + 32, y + 43, size=title_size, weight=650, fill=palette["text"]))
            number = str(public)
            parts.append(typeset.run(number, x + 32, y + 79, size=34, weight=700, fill=number_fill))
            number_width = typeset.measure(number, 34, 700)
            noun = "public repository" if public == 1 else "public repositories"
            parts.append(
                typeset.run(noun, x + 32 + number_width + 10, y + 78, size=16, weight=400, fill=palette["label"])
            )
            parts.append(typeset.run(portfolio["tagline"], x + 32, y + 117, size=14, weight=400, fill=palette["faint"]))
        else:
            line_fill = palette["gold2"] if accent == "gold" else palette["tealtext"]
            parts.append(typeset.run(title, x + 35, y + 44, size=21, weight=650, fill=palette["text"]))
            total = public + private
            line = f"{_plural(total, 'repository')} · {portfolio['tagline']}"
            parts.append(typeset.run(line, x + 35, y + 84, size=17, weight=400, fill=line_fill))
        cards.append("    <g>\n      " + "\n      ".join(parts) + "\n    </g>")

    heading = typeset.run("PORTFOLIO ECOSYSTEM", 60, 52, size=28, weight=650, fill=palette["text"], letter_spacing=3)
    summary = f"{counts.repositories} REPOSITORIES · {counts.portfolios} INDEPENDENT GROUPS"
    summary_run = typeset.run(
        summary, 1140, 50, size=15, weight=400, fill=palette["label"], letter_spacing=1.4, anchor="end"
    )
    footer = typeset.run(
        "CONTRACT FLOW · EVIDENCE FLOW · INDEPENDENT OWNERSHIP",
        600,
        675,
        size=14,
        weight=400,
        fill=palette["faint"],
        letter_spacing=1.5,
        anchor="middle",
    )
    licence = LICENCE_HEADER.format(purpose=f"Anulum portfolio ecosystem map, {theme} theme")
    intro = (
        f"{counts.portfolios} independent repository portfolios connected by integration, "
        "evidence, and audit relationships."
    )
    return f"""{licence}<svg {SVG_NAMESPACES} width="1200" height="700" viewBox="0 0 1200 700"
     role="img" aria-labelledby="title description">
  <title id="title">Anulum portfolio ecosystem</title>
  <desc id="description">{intro} {counts.desc()}</desc>
  <defs>
    {typeset.defs()}
    <linearGradient id="background" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{palette["bg0"]}"/>
      <stop offset="0.55" stop-color="{palette["bg1"]}"/>
      <stop offset="1" stop-color="{palette["bg2"]}"/>
    </linearGradient>
    <linearGradient id="gold" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="{palette["gold"]}"/>
      <stop offset="1" stop-color="{palette["gold2"]}"/>
    </linearGradient>
    <linearGradient id="teal" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="{palette["teal2"]}"/>
      <stop offset="1" stop-color="{palette["teal"]}"/>
    </linearGradient>
    <marker id="arrowGold" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth">
      <path d="M0,0 L0,6 L9,3 z" fill="{palette["gold"]}"/>
    </marker>
    <marker id="arrowTeal" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth">
      <path d="M0,0 L0,6 L9,3 z" fill="{palette["teal"]}"/>
    </marker>
  </defs>

  <rect width="1200" height="700" rx="28" fill="url(#background)" stroke="{palette["grid"]}" stroke-opacity="0.3"/>
  <g fill="none" stroke="{palette["grid"]}" stroke-opacity="0.14" stroke-width="1">
    <path d="M0 88H1200M0 294H1200M0 486H1200M0 650H1200"/>
    <path d="M200 0V700M400 0V700M600 0V700M800 0V700M1000 0V700"/>
  </g>

{heading}
{summary_run}

  <g fill="none" stroke-linecap="round" stroke-width="2.5">
    <path d="M230 254 C250 300 360 316 440 350" stroke="{palette["gold"]}" marker-end="url(#arrowGold)"/>
    <path d="M600 254 L600 330" stroke="{palette["gold"]}" marker-end="url(#arrowGold)"/>
    <path d="M970 254 C950 300 840 316 760 350" stroke="{palette["gold"]}" marker-end="url(#arrowGold)"/>
    <path d="M600 446 L600 514" stroke="{palette["teal"]}" marker-end="url(#arrowTeal)"/>
    <path d="M190 254 C150 430 270 555 360 580" stroke="{palette["teal"]}" stroke-dasharray="7 9"
          marker-end="url(#arrowTeal)"/>
    <path d="M1010 254 C1050 430 930 555 840 580" stroke="{palette["teal"]}" stroke-dasharray="7 9"
          marker-end="url(#arrowTeal)"/>
  </g>

  <g>
{chr(10).join(cards)}
  </g>

{footer}
</svg>
"""


def render_all(data: dict[str, Any]) -> dict[Path, str]:
    """Render every output file into memory."""
    typeset = Typesetter(FONT_FILES)
    counts = load_counts(data)
    rendered: dict[Path, str] = {}
    for (kind, theme), path in OUTPUTS.items():
        renderer = render_header if kind == "header" else render_map
        rendered[path] = renderer(data, theme, typeset, counts)
    return rendered


def main(argv: list[str] | None = None) -> int:
    """Write the SVGs, or with ``--check`` verify the committed files are current."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if any committed SVG differs from a fresh render")
    args = parser.parse_args(argv)

    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    rendered = render_all(data)
    if args.check:
        stale = [
            path for path, text in rendered.items() if not path.is_file() or path.read_text(encoding="utf-8") != text
        ]
        for path in stale:
            print(f"ERROR: stale or missing rendered asset: {path.relative_to(ROOT)}")
        if stale:
            return 1
        print(f"Rendered assets are current: {len(rendered)} files.")
        return 0
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)} ({len(text.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
