#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render the static badges of the READMEs as local SVG files.

``tools/badges.json`` lists every static badge (language selector, links,
languages, practices, counts) with its style, colour, label and message. Text may
carry ``{stats.<key>}`` placeholders resolved from ``profile-data.json`` so counts
cannot drift from the manifest. Badges whose wording differs per language carry a
``lang`` and render to ``assets/badges/<slug>.<lang>.svg``; the others render to
``assets/badges/<slug>.svg``. Text is outlined in Space Grotesk like the header
and the ecosystem map. Only the registry-driven badges (PyPI version, CI status)
stay external.

Usage: ``python3 tools/render_badges.py [--check]``
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from render_profile_assets import FONT_FILES, ROOT, Typesetter

SPEC = ROOT / "tools" / "badges.json"
CJK_FONTS = {
    "zh": ROOT / "assets" / "fonts" / "noto-sans-cjk-sc-subset.otf",
    "ja": ROOT / "assets" / "fonts" / "noto-sans-cjk-jp-subset.otf",
}
MANIFEST = ROOT / "profile-data.json"
OUT_DIR = ROOT / "assets" / "badges"
LICENCE = (
    "<!-- SPDX-License-Identifier: AGPL-3.0-or-later | © 2020–2026 Miroslav Šotek | "
    "generated by tools/render_badges.py from tools/badges.json; do not edit by hand -->\n"
)
LABEL_BACKGROUND = "#555555"
LIGHT_TEXT = "#ffffff"
DARK_TEXT = "#222222"


def luminance(hex_colour: str) -> float:
    """Relative luminance (0..1) of a ``RRGGBB`` colour, sRGB approximation."""
    r, g, b = (int(hex_colour[i : i + 2], 16) / 255 for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def text_colour(background: str) -> str:
    """Dark text on light backgrounds, light text otherwise."""
    return DARK_TEXT if luminance(background) > 0.6 else LIGHT_TEXT


def resolve(text: str, data: dict[str, Any]) -> str:
    """Resolve ``{stats.key}`` placeholders from the manifest."""
    out = text
    while "{stats." in out:
        start = out.index("{stats.")
        end = out.index("}", start)
        key = out[start + 7 : end]
        out = out[:start] + str(data["stats"][key]) + out[end + 1 :]
    return out


def output_path(entry: dict[str, Any]) -> Path:
    """Where a badge entry renders to."""
    suffix = f".{entry['lang']}" if entry.get("lang") else ""
    return OUT_DIR / f"{entry['slug']}{suffix}.svg"


def font_stack(entry: dict[str, Any]) -> tuple[Path, ...]:
    """Space Grotesk, plus the Noto Sans CJK subset for Chinese or Japanese wording."""
    script = entry.get("script") or entry.get("lang") or ""
    return FONT_FILES + ((CJK_FONTS[script],) if script in CJK_FONTS else ())


def render_badge(entry: dict[str, Any], data: dict[str, Any], typeset: Typesetter) -> str:
    """Return the SVG text of one badge in shields.io's flat-square or for-the-badge geometry."""
    style = entry["style"]
    colour = "#" + entry["colour"].lower()
    label = resolve(entry.get("label", ""), data)
    message = resolve(entry["message"], data)
    if style == "for-the-badge":
        height, size, weight, spacing, pad = 28, 10.0, 700, 1.4, 12.0
        label, message = label.upper(), message.upper()
    else:
        height, size, weight, spacing, pad = 20, 11.0, 500, 0.0, 6.0
    typeset.reset()
    label_width = typeset.measure(label, size, weight, spacing) + 2 * pad if label else 0.0
    message_width = typeset.measure(message, size, weight, spacing) + 2 * pad
    total = label_width + message_width
    baseline = height / 2 + size * 0.36
    parts: list[str] = []
    if label:
        parts.append(f'<rect width="{label_width:.1f}" height="{height}" fill="{LABEL_BACKGROUND}"/>')
    parts.append(f'<rect x="{label_width:.1f}" width="{message_width:.1f}" height="{height}" fill="{colour}"/>')
    if label:
        parts.append(
            typeset.run(
                label,
                label_width / 2,
                baseline,
                size=size,
                weight=weight,
                fill=LIGHT_TEXT,
                letter_spacing=spacing,
                anchor="middle",
            )
        )
    parts.append(
        typeset.run(
            message,
            label_width + message_width / 2,
            baseline,
            size=size,
            weight=weight,
            fill=text_colour(entry["colour"]),
            letter_spacing=spacing,
            anchor="middle",
        )
    )
    title = f"{label}: {message}" if label else message
    title = title.replace("&", "&amp;").replace("<", "&lt;")
    return (
        f'{LICENCE}<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'width="{total:.0f}" height="{height}" viewBox="0 0 {total:.1f} {height}" role="img" aria-label="{title}">'
        f"<title>{title}</title><defs>{typeset.defs()}</defs>{''.join(parts)}</svg>\n"
    )


def render_all(data: dict[str, Any], spec: list[dict[str, Any]]) -> dict[Path, str]:
    """Render every badge of the spec into memory."""
    typesetters: dict[tuple[Path, ...], Typesetter] = {}
    rendered: dict[Path, str] = {}
    for entry in spec:
        path = output_path(entry)
        if path in rendered:
            raise ValueError(f"duplicate badge output: {path.name}")
        stack = font_stack(entry)
        typeset = typesetters.setdefault(stack, Typesetter(stack))
        rendered[path] = render_badge(entry, data, typeset)
    return rendered


def main(argv: list[str] | None = None) -> int:
    """Write the badges, or with ``--check`` verify the committed files are current."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if any committed badge differs from a fresh render")
    args = parser.parse_args(argv)
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    rendered = render_all(data, spec)
    if args.check:
        stale = [p for p, text in rendered.items() if not p.is_file() or p.read_text(encoding="utf-8") != text]
        extra = sorted(set(OUT_DIR.glob("*.svg")) - set(rendered))
        for path in stale:
            print(f"ERROR: stale or missing badge: {path.relative_to(ROOT)}")
        for path in extra:
            print(f"ERROR: badge without a spec entry: {path.relative_to(ROOT)}")
        if stale or extra:
            return 1
        print(f"Badges are current: {len(rendered)} files.")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(rendered)} badges to {OUT_DIR.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
