#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Write ``PUBLICATIONS.md`` from the Zenodo cache and the manifest.

Every row comes from ``tools/feeds.json`` (refreshed by ``profile_feeds.py --refresh``):
titles, dates, resource types, versions and DOIs are Zenodo's own. The manifest adds
the project each record belongs to (``record_projects``) and the few status notes that
Zenodo cannot express (``publication_notes``). The framing paragraphs are fixed text.

Usage: ``python3 tools/render_publications.py [--check]``
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any

from profile_feeds import CACHE, MANIFEST, ROOT, resource_label

OUTPUT = ROOT / "PUBLICATIONS.md"

INTRO = """<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<!-- Generated by tools/render_publications.py from tools/feeds.json; do not edit by hand. -->

# Research And Publication Index

**Miroslav Šotek** · [ORCID {orcid_id}]({orcid}) · [GitHub]({github}) ·
[Publications hub on anulum.li](https://anulum.li/papers/) ·
[Releases and publications feed](https://anulum.li/news/)

Zenodo inventory read on {fetched}: {total} records whose creator carries the ORCID
above, {publications} of publication type and {software} software archives. "Published"
on this page means publicly deposited with a resolvable record. It does not imply
journal acceptance or peer review. Titles are the records' own.
"""

PUBLICATIONS_HEADING = """
## Publications And Preprints

| Date | Project | Output | Record type | Status | DOI |
|---|---|---|---|---|---|
"""

SOFTWARE_HEADING = """
## Software Archives

Latest archived version of each software record. Archived versions can lag PyPI or
GitHub releases; the version in this table is the one the cited record represents.

| Date | Software | Archived version | DOI |
|---|---|---:|---|
"""

CLOSING = """
## Manuscripts In Preparation

The portfolio also contains formal manuscript packages marked
`review_draft_not_submitted`. They are work in preparation, not publications or
submissions. Public release, DOI reservation, venue selection and submission
remain separate owner decisions.

## Citation Boundary

Use the citation file, release metadata or DOI attached to the specific project
state being discussed. Repository presence, a draft manuscript, a benchmark run
or a Zenodo deposit must not be silently promoted into peer review, independent
validation, production readiness or broad scientific advantage.
"""


def doi_link(doi: str) -> str:
    """Markdown link for a DOI."""
    return f"[{doi}](https://doi.org/{doi})"


def render(data: dict[str, Any], cache: dict[str, Any]) -> str:
    """Return the complete Markdown page."""
    projects = data["record_projects"]
    notes = data["publication_notes"]
    records = cache["zenodo"]
    publications = [record for record in records if record["type"].startswith("publication/")]
    software = [record for record in records if record["type"].startswith("software/")]
    unknown = [record["id"] for record in records if str(record["id"]) not in projects]
    if unknown:
        raise ValueError(f"records without a project in the manifest: {unknown}")

    lines = [
        INTRO.format(
            orcid=data["profile"]["orcid"],
            orcid_id=data["profile"]["orcid"].rsplit("/", 1)[-1],
            github=data["profile"]["github"],
            fetched=cache["fetched_at"],
            total=len(records),
            publications=len(publications),
            software=len(software),
        ),
        PUBLICATIONS_HEADING,
    ]
    for record in publications:
        status = notes.get(str(record["id"]), "Deposited")
        lines.append(
            f"| {record['date']} | {projects[str(record['id'])]} | {record['title']} | {resource_label(record)} | "
            f"{status} | {doi_link(record['doi'])} |\n"
        )
    lines.append(SOFTWARE_HEADING)
    for record in software:
        version = record["version"] or "n/a"
        lines.append(f"| {record['date']} | {projects[str(record['id'])]} | {version} | {doi_link(record['doi'])} |\n")
    lines.append(CLOSING)
    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Write PUBLICATIONS.md, or with ``--check`` verify it is current."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if PUBLICATIONS.md differs from a fresh render")
    args = parser.parse_args(argv)
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    cache = json.loads(CACHE.read_text(encoding="utf-8"))
    text = render(data, cache)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
            print("ERROR: PUBLICATIONS.md is out of date (run tools/render_publications.py)")
            return 1
        print("PUBLICATIONS.md is current.")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(text.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
